# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict_my_money', '0003_auto_20161114_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=255)),
                ('current_diversity', models.FloatField(default=0)),
                ('total_invested', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Current Day')),
                ('value', models.IntegerField(default=0)),
                ('diversity', models.FloatField(default=0.0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict_my_money.Portfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='investor',
            name='liquid_assets',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='total_invested',
        ),
        migrations.RemoveField(
            model_name='stock_owned',
            name='user',
        ),
        migrations.AddField(
            model_name='investor',
            name='portfolios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict_my_money.Portfolio'),
        ),
        migrations.AddField(
            model_name='stock_owned',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict_my_money.Portfolio'),
        ),
    ]
