# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict_my_money', '0004_auto_20161123_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='portfolios',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict_my_money.Investor'),
        ),
    ]
