# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_my_money', '0005_auto_20161123_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='general_trend',
            new_name='current_adjusted_close',
        ),
        migrations.AddField(
            model_name='stock_day',
            name='adjustedClose',
            field=models.IntegerField(default=0),
        ),
    ]
