# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_my_money', '0006_auto_20161129_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Latest Record'),
        ),
    ]
