# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_my_money', '0007_auto_20161130_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Creation Date of Portfolio'),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
